#!/usr/bin/env bash
# Display information about subdomains

info_subdomain () {
    if [ -z "$2" ]
    then
	SUBDOMAINS=(www lb-01 web-01 web-02)
	for subdomain in "${SUBDOMAINS[@]}";
	do
	    COMPLETE_DOMAIN="$subdomain.$1"
	    dig "$COMPLETE_DOMAIN" | grep -A1 "ANSWER SECTION:" | tail -n 1 > dig_result
	    awk -v the_subdomain="$subdomain" '/I/ {print "The subdomain " the_subdomain " is a " $4 " record and points to " $5}' dig_result
	    rm dig_result
	done
    else
	COMPLETE_DOMAIN="$2.$1"
	dig "$COMPLETE_DOMAIN" | grep -A1 "ANSWER SECTION:" | tail -n 1 > dig_result
	awk -v subdomain="$2" '/I/ {print "The subdomain " subdomain " is a " $4 " record and points to " $5}' dig_result
	rm dig_result
    fi

    exit 0
}

info_subdomain "$1" "$2"
