#!/usr/bin/env bash
# Installing nginx web server

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Reads the string following -c option as a command
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
