#!/usr/bin/env bash
# Installing nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
# Reads the string following -c option as a command
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
