#!/usr/bin/env bash
# install nginx on web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.back
sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-avaialable/default
sudo /etc/init.d/nginx restart
