#!/usr/bin/env bash
# install and configure nginx on web-01 server to redirect /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.back

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error-404.html

sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\terror_page 404 \/error-404.html;\n\tlocation = \/error-404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;}/" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
