#!/usr/bin/env bash
# This script installs and configure HAproxy load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
sudo bash -c 'echo "ENABLED=1" >> /etc/default/haproxy'
sudo bash -c 'echo -e "\nfrontend airbnb_main\n\tbind *:80\n\tdefault_backend airbnb_backend\n\nbackend airbnb_backend\n\tbalance roundrobin\n\tserver 236263-web-01 34.229.72.86:80 check\n\tserver 236263-web-02 54.83.130.153:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
