#!/usr/bin/env bash
# This script installs and configure HAproxy load balancer

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
sudo bash -c 'echo "ENABLED=1" >> /etc/default/haproxy'
sudo bash -c 'echo "no option http-use-htx" >> /etc/haproxy/haproxy.cfg'
sudo bash -c 'echo -e "\nfrontend airbnb_main\n\tbind *:80\n\tdefault_backend airbnb_backend\n\nbackend airbnb_backend\n\tbalance roundrobin\n\tserver 236263-web-01 54.210.174.151:80 check\n\tserver 236263-web-02 18.235.234.102:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
