#!/usr/bin/env bash
# Automate debugging procedure

sudo apt-get -y update;
#sudo apt-get -y install nginx;
sudo sed -i "s/listen 8080;/listen 80;/" /etc/nginx/sites-available/default;
sudo service nginx restart;
