#!/usr/bin/env bash
#Bash scipt that displays number from 1 to 100
#printing fizz when the number is a multiple of 3
#printing Buzz when the number is a multiple of 5
#and FizzBuzz when the number is a multiple of 3 and 5
number=1
for number in {1..100};
do
	if [ $(( (number % 15) )) -eq 0 ];
	then
		echo "FizzBuzz";
	elif [ $(( (number % 3) )) -eq 0 ];
	then
		echo "Fizz";
	elif [ $(( (number % 5) )) -eq 0 ];
      	then
		echo "Buzz";
	else
		echo "$number";
	fi
done
