#!/usr/bin/env bash
#Printing  numbers from 1 to 20 exept at 4th, 9th, and 17th iteration
i=0
while [ $i -le 19 ];
do
	i=$(( i + 1 ));
	echo "$i";
	case $i in 4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
done
