#!/usr/bin/env bash
#Bash script that print some basic information about 'school' file
if [ -e school ];
then
	echo "school file exists";

	wc -c school > num_char;
	string=$(cut -d " " -f 1 num_char);
	if [ "$string" -eq 0 ];
	then
		echo "school file is empty";
	else
		echo "school file is not empty";
	fi

	if [ -f school ];
	then
		echo "school is a regular file";
	fi
	rm num_char;
else
	echo "school file does not exist";
fi
