#!/usr/bin/env bash
# Script that changes the IP address of localhost and facebook.com

# Check if the hosts file exist
# If yes, open the hosts file
# locate the line where localhost is found
# change the IP to 127.0.0.2
# check if facebook.com entry exist in the file
# if yes, update the IP address to 8.8.8.8
# if no, append the line "8.8.8.8	facebook.com" to the hosts file
if [ -f /etc/hosts ]
then
	cp /etc/hosts ./hosts.new;
	sudo sed -i 's/127.0.0.[0-9]\slocalhost/127.0.0.2	localhost\n8.8.8.8	facebook.com/g' hosts.new;
	sudo cp ./hosts.new  /etc/hosts;
	rm ./hosts.new;
fi
