#!/usr/bin/env bash
# Fixing container so that Nginx is running as the nginx user.
sudo chmod o+r /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
