#!/usr/bin/env bash
# Run Nginx as user nginx
sudo chmod o+r /etc/nginx/nginx.conf
sudo su nginx -c 'service nginx start'
LISTEN_DIRECTIVE=$(grep -A1 "^server {" /etc/nginx/sites-available/default | tail -n 1)
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo su nginx -c 'service nginx restart'
